build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: "https://conan.campar.in.tum.de/api/conan/conan-camposs"
    CONAN_REMOTES: "https://conan.campar.in.tum.de/api/conan/conan-camposs"
    CONAN_REFERENCE: "transwarp/1.8.0"
    CONAN_USERNAME: "camposs"
    CONAN_CHANNEL: "stable"
    CONAN_STABLE_BRANCH_PATTERN: "release/*"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py